### ISSUE TITLE
Ĝisdatigu la datumbazon

### ISSUE THREAD

**Issue by mayhair** [djuretic/praktika-vortaro#3]
La datumbazo de ĉi tiu apo estis laste ĝisdatigita antaŭ pli ol unu jaro (2022-12-05). Ĉu vi povas ĝisdatigi ĝin nun, por ke oni profitos de la lastaj redaktoj?

Aŭ eble vi povas enigi funkcion, kiu lasas la uzanton elŝuti la plej novan datumbazon.

**Comment by djuretic** [comment]
@mayhair pardonu la malfruecon! Mi ĝisdatigis la datumbazon, ĝisdatigu la apon kaj provu ĝin.
